# Generated by Django 2.1.3 on 2018-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181125_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readed_num',
            field=models.IntegerField(default=0, verbose_name='阅读计数'),
        ),
    ]
